# Generated by Django 2.0.4 on 2018-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_text',
            new_name='nome_Cliente',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_text',
            new_name='nome_Funcionario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id_funcionario',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='id_livro',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CPF_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Tel_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='CPF_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Tel_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livros',
            name='quantidade_paginas',
            field=models.CharField(max_length=255),
        ),
    ]
